#!/bin/bash
cd ~/work/device/xiaomi/*/prebu*
aria2c https://github.com/RT1648/Extras/releases/download/14.0.3.0.TEKMIXM/vendor.img
ls
cd ~/work
. build/envsetup.sh
$EXTRA_CMD
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
lunch "$LUNCH_COMBO"
$EXTRA_CMD1
make $TARGET -j8 & sleep 60m
