#!/bin/bash
cd ~/work/device/xiaomi/fleur/prebuilts
aria2c https://github.com/RT1648/Extras/releases/download/13.0.8.0.SKEMIXM/vendor.img
ls
cd ~/work
#rm -rf system/bpf
#git clone https://github.com/PixelExperience/system_bpf.git system/bpf
rm -rf android/frameworks/av
git clone https://github.com/DerpFest-AOSP/frameworks_av.git android/frameworks/av 
rm -rf android/packages/modules/Bluetooth
https://github.com/DerpFest-AOSP/packages_modules_Bluetooth.git android/packages/modules/Bluetooth 
. build/envsetup.sh
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 90G
ccache -o compression=true
ccache -z
lunch "$LUNCH_COMBO"
mka $TARGET -j$(nproc --all) & sleep 90m
